// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOKtXDvxHS1Wm4BjLkuF97CxjllROpIDs',
    appId: '1:536625700874:web:6c05fc6903b5aa7041fff3',
    messagingSenderId: '536625700874',
    projectId: 'marynews-7deae',
    authDomain: 'marynews-7deae.firebaseapp.com',
    storageBucket: 'marynews-7deae.appspot.com',
    measurementId: 'G-FSWP9SY0P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvpJyKXHT-lhEJWsuKQasV9VWs9SQ5ppc',
    appId: '1:536625700874:android:30df0cc9ee02972141fff3',
    messagingSenderId: '536625700874',
    projectId: 'marynews-7deae',
    storageBucket: 'marynews-7deae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAZqvmW1wjMDWs72Bzu9vxmxy0oODf360',
    appId: '1:536625700874:ios:eea14b67c95a7c2841fff3',
    messagingSenderId: '536625700874',
    projectId: 'marynews-7deae',
    storageBucket: 'marynews-7deae.appspot.com',
    iosBundleId: 'com.example.maryNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAZqvmW1wjMDWs72Bzu9vxmxy0oODf360',
    appId: '1:536625700874:ios:8fd4c48a3ad27c9a41fff3',
    messagingSenderId: '536625700874',
    projectId: 'marynews-7deae',
    storageBucket: 'marynews-7deae.appspot.com',
    iosBundleId: 'com.example.maryNews.RunnerTests',
  );
}
